Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :admins, :controller => "admins"
   match 'admins/:id' => 'admins#destroy', :via => :delete, :as => :admin_destroy
 
  resources :zones do
      resources :proyects do
          resources :spends
          match 'spends/:status' => 'spends#status', :via => :post, :as => :spend_status
          resources :lista
          resources :viaticos
          match 'viaticos/:status' => 'viaticos#status', :via => :post, :as => :viatico_status
          resources :brokers
      end
  end
  

  get 'welcome/index'

  root 'welcome#index'

end

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/models/broker.rb
class Broker < ActiveRecord::Base
  belongs_to :user
  belongs_to :proyect
  include Scope
end

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/controllers/brokers_controller.rb
class BrokersController < ApplicationController
  before_action :set_broker, only: [:destroy]
  before_action :auth
  before_action :set_proyect

  # GET /brokers.json



  # GET /brokers/new
  def new
    @broker = Broker.new
    @notuser = Array.new(User.joins(:brokers).proyecto(@proyect))
    @user = Array.new(User.usuario_inactivo)
   
    @notuser.each do |s|
      @user.delete_if {|x| x.id == s.id }
    end
  end

  # GET /brokers/1/edit


  # POST /brokers
  # POST /brokers.json
  def create
    @broker = Broker.new(broker_params)
    @broker.proyect = @proyect
    respond_to do |format|
      if @broker.save
        format.html { redirect_to [@zone,@proyect], notice: 'Broker agregado al proyecto.' }
        format.json { render :show, status: :created, location: @broker }
      else
        format.html { render :new }
        format.json { render json: @broker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brokers/1
  # PATCH/PUT /brokers/1.json


  # DELETE /brokers/1
  # DELETE /brokers/1.json
  def destroy
    @broker.destroy
    respond_to do |format|
      format.html { redirect_to [@zone,@proyect], notice: 'Broker eliminado del proyecto.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_broker
      @broker = Broker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def broker_params
      params.require(:broker).permit(:user_id, :proyect_id)
    end
    def set_proyect
      @proyect = Proyect.find(params[:proyect_id])
      @zone = Zone.find(params[:zone_id])
    end
end

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/helpers/brokers_helper.rb
module BrokersHelper
end

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/views/brokers/_form.html.erb
<%= form_for([@zone,@proyect,@broker]) do |f| %>
  <% if @broker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@broker.errors.count, "error") %> prohibited this broker from being saved:</h2>

      <ul>
      <% @broker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%if not @user.empty?%>
    <div class="form-group dates">
      <%= f.label :user_id, "Correo de Usuario" %><br>
        <%= f.select(:user_id) do %>
          <% @user.each do |c| %>
            <%= content_tag(:option, c.email, value: c.id) %>
          <% end %>
        <%end%>
    </div>
    <div class="actions">
      <%= f.submit "Agregar Broker" , class: 'btn btn-primary btn-sm guardar'%>
    </div>
    <%else%>
    <div class="alert alert-danger center">
      !Todos los usuarios pertenecen a este proyecto
    </div>
  <%end%>
<% end %>

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/views/brokers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Brokers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Proyect</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brokers.each do |broker| %>
      <tr>
        <td><%= broker.user %></td>
        <td><%= broker.proyect %></td>
        <td><%= link_to 'Show', broker %></td>
        <td><%= link_to 'Edit', edit_broker_path(broker) %></td>
        <td><%= link_to 'Destroy', broker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Broker', new_broker_path %>

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/views/brokers/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <h2 class="proyect_name alert alert-info">
    	<strong>Broker Nuevo<</strong> 
  	</h2>
	<div class="space_form">
		<%= render 'form' %>
	</div>
	<%= link_to ' Regresar', [@zone,@proyect], class: "btn btn-info float_right " %>
</div>