Proyectos/Viaticos/03. Desarrollo/Desarrollo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :admins, :controller => "admins"
   match 'admins/:id' => 'admins#destroy', :via => :delete, :as => :admin_destroy
 
  resources :zones do
      resources :proyects do
          resources :spends
          match 'spends/:status' => 'spends#status', :via => :post, :as => :spend_status
          resources :lista
          resources :viaticos
          match 'viaticos/:status' => 'viaticos#status', :via => :post, :as => :viatico_status
          resources :brokers
      end
  end
  

  get 'welcome/index'

  root 'welcome#index'

end

Proyectos/Viaticos/03. Desarrollo/Desarrollo/app/models/zone.rb
class Zone < ActiveRecord::Base
	validates :name, presence: true, uniqueness:  true
	has_many :proyects	
end

Proyectos/Viaticos/03. Desarrollo/Desarrollo/app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :auth
  before_action :set_zone, only: [:show, :edit, :update, :destroy]
  before_action :autenticacion_admin!, only: [:destroy]
  before_action :authenticate_user!, except: [:destroy]

  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
    @proyect = Proyect.new
    if current_user.is_admin?
      @broker = Proyect.all.ultimos.zona(@zone)
    else
      @broker = Broker.broker(current_user.id).ultimos
    end
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Área creada exitosamente' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Área actualizada exitosamente' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:name)
    end
end

Proyectos/Viaticos/03. Desarrollo/Desarrollo/app/helpers/zones_helper.rb
module ZonesHelper
end

Proyectos/Viaticos/03. Desarrollo/Desarrollo/app/views/zones/_admin.html.erb
<div class="table-responsive">
  <table class="table table-bordered">
    <caption class="top-center">
      <strong>Lista de Proyectos</strong>
    </caption>
    <thead>
      <tr>
        <th>Proyecto</th>
        <th>Administrador de proyecto</th>
      </tr>
    </thead>

    <tbody>
      <%@valor = 0%>
      <% @broker.each do |proyecto| %>
          <%= render "parcial/color"%>
            <td><%= link_to proyecto.name, [@zone, proyecto]%></td>
            <td><%= proyecto.user.email%></td>
            <td>
              <%= link_to 'Editar', edit_zone_proyect_path(@zone, proyecto)%>
            </td>
            <td><% link_to 'Eliminar', [@zone,proyecto], method: :delete, data: { confirm: 'Estas seguro?' } %></td>
          </tr>
        <%end%>
    </tbody>
  </table>
</div>
  <%= link_to ' Editar', edit_zone_path(@zone) ,class: "btn btn-warning fa fa-edit"%>

Proyectos/Viaticos/03. Desarrollo/Desarrollo/app/views/zones/_form.html.erb
<%= form_for(@zone) do |f| %>
  <% if @zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% @zone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name , "Nombre" %><br>
    <%= f.text_field :name ,placeholder: "Nombre de Area", class: "form-control" ,required: "required"%>
  </div>
  <div class="actions">
    <%= f.submit  "Guardar" , class: 'btn btn-primary btn-sm guardar'%>
  </div>
<% end %>

Proyectos/Viaticos/03. Desarrollo/Desarrollo/app/views/zones/_normal_user.html.erb
<div class="table-responsive">
  <table class="table table-bordered">
    <caption class="top-center">
      <strong>Lista de Proyectos</strong>
    </caption>
    <thead>
      <tr>
        <th>Proyecto</th>
        <th>Administrador de proyecto</th>
      </tr>
    </thead>

    <tbody>
      <%@valor = 0%>
      <% @broker.each do |proyecto| %>
        <%if proyecto.proyect.zone_id == @zone.id%>
          <%= render "parcial/color"%>
            <td><%= link_to proyecto.proyect.name, [@zone, proyecto.proyect]%></td>
            <td><%= proyecto.proyect.user.email%></td>
            <%if current_user.email == proyecto.proyect.user.email || current_user.is_admin? %>
            <td>
              <%= link_to 'Editar', edit_zone_proyect_path(@zone, proyecto.proyect)%>
            </td>
            <%end%>
          </tr>
        <%end%>
      <% end %>
    </tbody>
  </table>
  </div>

Proyectos/Viaticos/03. Desarrollo/Desarrollo/app/views/zones/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	<h2 class="proyect_name alert alert-info">
    	<strong>Editando Área de proyectos</strong> 
  	</h2>
	<div class="space_form">
		<%= render 'form' %>
	</div>
	<%= link_to 'Ir a Area de proyecto', [@zone],class: "btn btn-primary" %> 
	<%= link_to ' Regresar', zone_path, class: "btn btn-info float_right " %>
</div>

Proyectos/Viaticos/03. Desarrollo/Desarrollo/app/views/zones/index.html.erb
<div class="col-md-8 col-md-pushed-2 col-md-offset-2">
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <h2 class="proyect_name alert alert-info">
    <strong>Áreas de proyectos</strong>
  </h2>
  <%= link_to ' Crear Area', new_zone_path ,class: "btn btn-primary fa fa-plus edit "%>
  <div class="table-responsive">
    <table class="table table-bordered">
      <caption class="top-center">
        <strong>Lista de Áreas</strong>
      </caption>
      <thead>
        <tr>
          <th>Nombre de Área</th>
        </tr>
      </thead>

      <tbody>
        <%@valor = 0%>
        <% @zones.each do |zone| %>
          <%= render "parcial/color"%>
            <td><%= link_to zone.name, [zone,@proyect] %></td>
            <%if current_user.is_admin? %>
              <td><%= link_to 'Editar', edit_zone_path(zone) %></td>
            <%end%>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

Proyectos/Viaticos/03. Desarrollo/Desarrollo/app/views/zones/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	<h2 class="proyect_name alert alert-info">
    	<strong>Crear Área de proyectos</strong> 
  	</h2>
	<div class="space_form">
		<%= render 'form' %>
	</div>
	<%= link_to 'Regresar', zones_path, class: "btn btn-info float_right " %>
</div>

Proyectos/Viaticos/03. Desarrollo/Desarrollo/app/views/zones/show.html.erb
<div class="col-md-10 col-md-pushed-1 col-md-offset-1">
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <h2 class="proyect_name alert alert-info">
    <strong><%= @zone.name %></strong>
  </h2>
  <%= link_to ' Crear proyecto', new_zone_proyect_path(@zone) ,class: "btn btn-primary fa fa-plus edit "%>

  <%= link_to ' Regresar', zones_path ,class: "btn btn-info fa fa-arrow-left float_right "%>

    <%if current_user.is_admin?%>
      <%= render 'admin' %>
    <%else%>
      <%= render 'normal_user' %>
    <%end%>
</div>