Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :admins, :controller => "admins"
   match 'admins/:id' => 'admins#destroy', :via => :delete, :as => :admin_destroy
 
  resources :zones do
      resources :proyects do
          resources :spends
          match 'spends/:status' => 'spends#status', :via => :post, :as => :spend_status
          resources :lista
          resources :viaticos
          match 'viaticos/:status' => 'viaticos#status', :via => :post, :as => :viatico_status
          resources :brokers
      end
  end
  

  get 'welcome/index'

  root 'welcome#index'

end

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/models/spend.rb
class Spend < ActiveRecord::Base
  validates :tipo, presence: true
  validates :importe, presence: true, numericality: true
  
  belongs_to :proyect
  belongs_to :user
  has_attached_file :ticket, :styles => { :medium => "900x600>", :thumb => "600x900>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :ticket, :content_type => /\Aimage\/.*\Z/
  
  #scopes
  include Scope
end

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/controllers/spends_controller.rb
class SpendsController < ApplicationController
  before_action :auth
  before_action :set_spend, only: [:show, :edit, :update, :destroy]
  before_action :set_proyect
  before_action :autenticacion_admin!, only: [:destroy]
  # GET /spends
  # GET /spends.json
  def index
    
    @val = params[:xls]
    unless @val.blank?
      @spends = Spend.calendario(@val[:inicio],@val[:fin]).activos.usuario(current_user.id)
      @viaticos = Viatico.calendario(@val[:inicio],@val[:fin]).activos.usuario(current_user.id)
      unless @viaticos.blank?
        @total = 0
        @viaticos.each do |total|
            @total = @total + total.cantidad
        end
        respond_to do |format|
          format.html
          format.xlsx #{send_data @spends.to_csv(col_sep:'\t')}
        end
      end
      unless @spends.present?
          flash[:notice] = "No existen datos en la busqueda solicitada" 
      end
    end
  end 
  
  def show
  end

  def status
    spend = Spend.find_by(id: params[:status])
    spend.status = 1
    if spend.save
      respond_to do |format|
        format.html { redirect_to [@zone,@proyect], notice: "Gasto Reportado correctamente" }
      end
    end
    
  end


  # GET /spends/new
  def new
    @spend = Spend.new
  end

  # GET /spends/1/edit
  def edit
  end

  # POST /spends
  # POST /spends.json
  def create
    @spend = current_user.spends.new(spend_params)
    @spend.proyect = @proyect
    respond_to do |format|
      if @spend.save
        format.html { redirect_to [@zone,@proyect], notice: 'Gasto incorporado correctamente' }
        format.json { render :show, status: :created, location: @spend }
      else
        format.html { render :new }
        format.json { render json: @spend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spends/1
  # PATCH/PUT /spends/1.json
  def update
    respond_to do |format|
      if @spend.update(spend_params)
        format.html { redirect_to [@zone,@proyect], notice: 'Gasto Actualizado' }
        format.json { render :show, status: :ok, location: @spend }
      else
        format.html { render :edit }
        format.json { render json: @spend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spends/1
  # DELETE /spends/1.json
  def destroy
    @spend.destroy
    respond_to do |format|
      format.html { redirect_to [@zone,@proyect], notice: 'Dato eliminado exitosamente' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spend
      @spend = Spend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spend_params
      params.require(:spend).permit(:proyect_id, :fecha, :tipo, :importe, :comntarios, :comprobante, :numero_comprobante, :user_id, :ticket,:status)
    end
    def set_proyect
      @proyect = Proyect.find(params[:proyect_id])
      @zone = Zone.find(params[:zone_id])
    end
    
end

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/helpers/spends_helper.rb
module SpendsHelper
end

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/views/spends/_form.html.erb
<%= form_for([@zone,@proyect,@spend]) do |f| %>
  <% if @spend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spend.errors.count, "error") %> prohibited this spend from being saved:</h2>

      <ul>
      <% @spend.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group date">
    <%= f.label :fecha %><br>
    <%= f.date_field :fecha ,required: "required"%>
  </div>
  <br>
  <div class="form-group dates">
    <%= f.label :tipo, "Tipo de gasto" %><br>
    <%= f.select(:tipo) do %>
      <%= content_tag(:option, "Alimentos", value: "Alimentos") %>
      <%= content_tag(:option, "Avión", value: "Avión") %>
      <%= content_tag(:option, "Adicionales Gasolina", value: "Adicionales Gasolina") %>
      <%= content_tag(:option, "Estacionamiento", value: "Estacionamiento") %>
      <%= content_tag(:option, "Hotel", value: "Hotel") %>
      <%= content_tag(:option, "Insumos de Oficina", value: "Insumos de Oficina") %>
      <%= content_tag(:option, "Taxi Local", value: "Taxi Local") %>
      <%= content_tag(:option, "Taxi (al/desde Aeropuerto)", value: "Taxi (al/desde Aeropuerto)") %>
      <%= content_tag(:option, "Transporte Terrestre", value: "Transporte Terrestre") %>
    <%end%>
  </div>
  <div class="form-group">
    <%= f.label :importe %><br>
    <%= f.text_field :importe , required: "required", class: "form-control", placeholder: "Dato numerico Ej. 123.98"%>
  </div>
  <% if @report == 1%>
    <%= f.label :status , "Reportado" %><br>
    <%= f.check_box :status%>
  <%end%>
  <div class="form-group">
    <%= f.label :comntarios , "Comentarios"%><br>
    <%= f.text_area :comntarios , class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :comprobante , "Se cuenta con comprobante" %><br>
    <%= f.check_box :comprobante %>
  </div>
  <div class="form-group">
    <%= f.label :numero_comprobante , "Numero de folio del comprobante" %><br>
    <%= f.text_field :numero_comprobante , class: "form-control"%>
  </div>
  <div class="form-group">
    Imagen de comprobante <%= f.file_field :ticket %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar" , class: 'btn btn-primary btn-sm guardar'  %>
  </div>
<% end %>

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/views/spends/_table.html.erb
<div class="table-responsive">
  <table class="table table-bordered top">
  <thead>
    <tr>
      <th>Reporte de gastos:</th>
      <th><%= @val[:inicio]%></th>
      <th><%= @val[:fin]%></th>
    </tr>
  </thead>
  <thead>
    <tr>
      <th>Nombre:</th>
      <th><%=current_user.email%></th>
      <th></th>
      <th></th>
      <th>Deposito Adelantado</th>
      <th>$ <%= @total %></th>
    </tr>
  </thead>
    <thead>
      <tr>
        <th >Comprobante</th>
        <th>Numero comprobante</th>
        <th>Proyecto</th>
        <th>Fecha</th>
        <th>Tipo de Gasto</th>
        <th>Importe</th>
        <th>Comentarios</th>
        <th>Ticket</th>
      </tr>
    </thead>

    <tbody>
   
      <% @spends.each do |spend| %>
        <tr>
          <% if spend.comprobante == 1%>
            <td>SI</td>
          <%else%>
            <td>NO</td>
          <%end%>
          <td><%= spend.numero_comprobante %></td>
          <td><%= spend.proyect.name %></td>
          <td><%= spend.fecha %></td>
          <td><%= spend.tipo %></td>
          <td><%= spend.importe %></td>
          <td><%= spend.comntarios %></td>
          <%if spend.ticket_file_name != nil%>
          <td><%= image_tag spend.ticket.url(:thumb)%></td>
          <%end%>
    
        </tr>
      <% end %>

    </tbody>
  </table>
</div>

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/views/spends/edit.html.erb
<% @report = 1%>
<div class="col-md-6 col-md-offset-3">
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	<h2 class="proyect_name alert alert-info">
    	<strong>Edicion de Gasto</strong> 
  	</h2>
	<div class="space_form">
		<%= render 'form' %>
	</div>
	<%= link_to ' Regresar', [@zone,@proyect], class: "btn btn-info float_right " %>
	<%= link_to 'Visualizar gasto', [@zone,@proyect,@spend],class: "btn btn-primary" %> 
</div>

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/views/spends/index.html.erb
<div class="col-md-6 col-md-offset-3">
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <h2 class="proyect_name alert alert-info">
    <strong>Generacion de Reporte Viaticos</strong> 
  </h2>
  <form method="get" action="" id= "index">
    <div class="form-group dates">
      <label for = 'inicio'>Fecha Inicio:</label>
      <%= date_field(:xls,:inicio) %>
    </div>
    <div class="form-group dates">
      <label for= "fin">Fecha Fin:</label>
      <%= date_field(:xls,:fin) %>
    </div>
    <div class="actions">
       <%= link_to 'Generar Reporte',  zone_proyect_spends_path(@zone,@proyect,request.parameters.merge({:format => :html})), :onclick => "$('#index').submit()" ,class: "btn btn-danger fa fa-file-excel-o edit "%>
    </div>
  </form>
  <%= link_to ' Regresar', [@zone,@proyect], class: "btn btn-info float_right " %>
</div>
<%unless  @spends.blank?%>
  <div class="col-md-12">
    <h2 class="proyect_name alert alert-info">
      <strong>Vista de Resultado</strong> 
    </h2>
    <%= link_to ' Descargar',  zone_proyect_spends_path(@zone,@proyect,request.parameters.merge({:format => :xlsx})), :onclick => "$('#index').submit()",class: "btn btn-success  margin-top fa fa-download edit "%>
    <div class="col-md-12">
      <%= render "table"%>
    </div>
  </div>

<%end%>

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/views/spends/index.xls.erb
<table>
  <tr>
    <th></th>
    <th>Reporte de gastos</th>
    <th></th>
    <th><%= @val[:inicio]%></th>
    <th>-</th>
    <th><%= @val[:fin]%></th>
    <th></th>
  </tr>
<tr></tr>
  <tr>
    <th>Nombre:</th>
    <th><%=current_user.email%></th>
    <th></th>
    <th></th>
    <th>Deposito Adelantado</th>
    <th>$ <%= @total %></th>
  </tr>
<tr></tr>
  <thead>
    <tr>
      <th >Comprobante</th>
      <th>Numero comprobante</th>
      <th>Proyecto</th>
      <th>Fecha</th>
      <th>Tipo de Gasto</th>
      <th>Importe</th>
      <th>Comentarios</th>
      <th>Ticket</th>
    </tr>
  </thead>

  <tbody>
 
    <% @spends.each do |spend| %>
      <tr>
        <% if spend.comprobante == 1%>
          <td>SI</td>
        <%else%>
          <td>NO</td>
        <%end%>
        <td><%= spend.numero_comprobante %></td>
        <td><%= spend.proyect.name %></td>
        <td><%= spend.fecha %></td>
        <td><%= spend.tipo %></td>
        <td><%= spend.importe %></td>
        <td><%= spend.comntarios %></td>
        <%if spend.ticket_file_name != nil%>
        <td><%= image_tag spend.ticket.url(:thumb)%></td>
        <%end%>
  
      </tr>
    <% end %>

  </tbody>
</table>

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/views/spends/new.html.erb
<% @report = 0%>
<div class="col-md-6 col-md-offset-3">
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	<h2 class="proyect_name alert alert-info">
    	<strong>Gasto nuevo</strong> 
  	</h2>
	<div class="space_form">
		<%= render 'form' %>
	</div>
	<%= link_to ' Regresar', [@zone,@proyect], class: "btn btn-info float_right " %>
</div>

Proyectos/Viaticos/Linea base/03. Desarrollo/Desarrollo/app/views/spends/show.html.erb
<div class="col-md-4 col-md-pushed-4 col-md-offset-4">
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <%if @spend.ticket_file_name != nil%>
    <a class="fancybox" rel="group" href="<%=@spend.ticket.url(:thumb)%>">
      <%= image_tag @spend.ticket.url(:thumb) , class: 'img-responsive img-circle'%>
    </a>
  <%end%>
</div>
<div class="col-md-12">
  <p id="notice"><%= notice %></p>

  <p>
  <div class="table-responsive">
    <table class="table table-bordered spacedor">
      <caption class="top-center">
        <strong>Gasto #<%=@spend.id%></strong>
      </caption>
      <thead>
          <tr>
            <th>Fecha</th>
            <th>Tipo</th>
            <th>Importe</th>
            <th>Comentarios</th>
            <th>Comprobante</th>
            <th>Numero comprobante</th>
            <th>Usuario</th>
          </tr>
      </thead>
      <tbody>
          <tr class="info">
            <td><%= @spend.fecha %></td>
            <td><%= @spend.tipo %></td>
            <td><%= @spend.importe %></td>
            <td><%= @spend.comntarios %></td>
            <% if @spend.comprobante == 1%>
              <td>SI</td>
            <%else%>
              <td>NO</td>
            <%end%>
            <td><%= @spend.numero_comprobante %></td>
            <td><%= @spend.user.email %></td>
            <%if current_user.is_admin? || current_user.email == @spend.user.email%>
                <td>
                  <%= link_to 'Editar', edit_zone_proyect_spend_path(@zone,@proyect,@spend)  %>
                </td>
            <%end%>
            <%if current_user.is_admin?%>
              <td><%= link_to 'Eliminar', [@zone,@proyect,@spend], method: :delete, data: { confirm: 'Estas seguro?' } %></td>
            <%end%>
          </tr>
       
      </tbody>
    </table>
  </div>

  <%= link_to 'Regresar', [@zone,@proyect], class: "btn btn-info fa fa-arrow-left float_right " %>
</div>